#!/usr/bin/env bash

if [ $# -eq 0 ]; then
	echo No post name passed
	return;
fi

mkdir "content/post/$1"
touch "content/post/$1/index.md"
cat << EOL >> "content/post/$1/index.md"
+++
author = "Anupam Kumar"
title = ""
date = ""
description = ""
tags = []
categories = []
aliases = []
image = ""
+++

EOL

