name: gh pages deploy

on:
  push:
    branches:
      - deploy

jobs:
  compile:
    uses: ./.github/workflows/gh-pages-compile.yml

  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy Step
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/deploy'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
