name: gh pages compile

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  compie:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

